"""initial

Revision ID: 47079c0f5b5c
Revises: 
Create Date: 2024-08-04 13:21:00.665088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47079c0f5b5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('file_size', sa.BIGINT(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('file_extension', sa.String(length=8), nullable=True),
    sa.Column('file_format', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
